name: coffee_hour
description: Aprende a hacer el mejor café tu mismo.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  flutter_swiper_view: ^1.1.8
  animate_do: ^2.1.0
  url_launcher: ^6.1.5

  scroll_app_bar: ^2.0.0

  share_plus: ^4.0.10+1

  freezed_annotation: ^2.1.0
 
  hydrated_bloc: ^8.1.0
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  path_provider: ^2.0.11

dev_dependencies:
  freezed: ^2.1.0+1
  build_runner: ^2.2.0
  json_serializable: ^6.3.1

  change_app_package_name: ^0.1.3

  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
 
  fonts:
    - family: Coffee-Tea
      fonts:
        - asset: assets/fonts/coffee+teademo-Regular.ttf

 